[package]
name = "result-like"
description = "Append Option/Result-like monad interface for your own enum"
version = "0.1.0"
documentation = "http://docs.rs/result-like"
repository = "https://github.com/youknowone/result-like"
authors = ["Jeong YunWon <jeong+resultlike@youknowone.org>"]
edition = "2018"
license = "2-clause BSD"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is-macro = "0.1"
